// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_p4JYaHulnn8m4ZHgzXYTI7aivaQ4OgQ',
    appId: '1:542782594602:web:e749973c752f11953aed53',
    messagingSenderId: '542782594602',
    projectId: 'miscuba-f5860',
    authDomain: 'miscuba-f5860.firebaseapp.com',
    storageBucket: 'miscuba-f5860.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZE5r0Rvlx63D9pQdm6t66evmCBIxhgzY',
    appId: '1:542782594602:android:442ab2a825855fef3aed53',
    messagingSenderId: '542782594602',
    projectId: 'miscuba-f5860',
    storageBucket: 'miscuba-f5860.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHxYhfZhmVvI6f-p1mImiaiYiCQTFnQjQ',
    appId: '1:542782594602:ios:0009466bf287b9f23aed53',
    messagingSenderId: '542782594602',
    projectId: 'miscuba-f5860',
    storageBucket: 'miscuba-f5860.appspot.com',
    iosBundleId: 'com.example.misuba2',
  );
}

// Push thos 