name: misuba2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  firebase_storage: ^11.6.5
  audioplayers: ^5.2.1
  geolocator: ^10.1.0
  location: ^5.0.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.15.4
  localstorage: ^4.0.1+4
  weather: ^3.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - asset/images/
     - asset/audio/
